In [5]:
#array creation
import numpy as np
array = np.array([1,2,3,4])
twod_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(type(array))
print(array)
print(array.size, twod_array.size)  # it returns size of an array
print(np.ndim(array), np.ndim(twod_array))  # it returns the dimensionality of an array

<class 'numpy.ndarray'>
[1 2 3 4]
4 9
1 2


In [7]:
# zeros array creation
zeros_array = np.zeros((2,3)) # it creates 2*3 matrix with zeros
print(zeros_array)
#1's array
ones_array = np.ones((3,3))
print(ones_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:
#indexing
import numpy as np
array = np.array([1,2,3,4])
twod_array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array[-1])
print(array[2:5])

4
[3 4]


In [11]:
# array operations
array = np.array([1,2,3,4])
array2 = np.array([5,6,7,8])
print(array + array2)
print(array - array2)
print(array * array2)
print(array ** 2)

[ 6  8 10 12]
[-4 -4 -4 -4]
[ 5 12 21 32]
[ 1  4  9 16]


In [13]:
# some statistical operations
array = np.array([1,2,3,4])
print(array.sum())
print(array.min())
print(array.max())
print(array.mean())
print(array.std())

10
1
4
2.5
1.118033988749895


In [14]:
import pandas as pd